export default {
  login: 'yuliyakasavec',
  id: 149088221,
  node_id: 'U_kgDOCOLn3Q',
  avatar_url: 'https://avatars.githubusercontent.com/u/149088221?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/yuliyakasavec',
  html_url: 'https://github.com/yuliyakasavec',
  followers_url: 'https://api.github.com/users/yuliyakasavec/followers',
  following_url:
    'https://api.github.com/users/yuliyakasavec/following{/other_user}',
  gists_url: 'https://api.github.com/users/yuliyakasavec/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/yuliyakasavec/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/yuliyakasavec/subscriptions',
  organizations_url: 'https://api.github.com/users/yuliyakasavec/orgs',
  repos_url: 'https://api.github.com/users/yuliyakasavec/repos',
  events_url: 'https://api.github.com/users/yuliyakasavec/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/yuliyakasavec/received_events',
  type: 'User',
  user_view_type: 'public',
  site_admin: false,
  name: 'Yuliya Kasavets',
  company: null,
  blog: '',
  location: 'Poland',
  email: null,
  hireable: null,
  bio: 'Frontend developer',
  twitter_username: null,
  public_repos: 40,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: '2023-10-26T14:54:10Z',
  updated_at: '2026-04-10T14:32:31Z',
};
