export default {
  login: 'yuliya-kasavets',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://clov.net/wimg/32574385521dd1847f7d1e5b940491ef.jpg',
  gravatar_id: '',
  url: 'https://api.github.com/users/yuliyakasavec',
  html_url: 'https://github.com/yuliyakasavec',
  followers_url: 'https://api.github.com/users/yuliyakasavec/followers',
  following_url:
    'https://api.github.com/users/yuliyakasavec/following{/other_user}',
  gists_url: 'https://api.github.com/users/yuliyakasavec/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/yuliyakasavec/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/yuliyakasavec/subscriptions',
  organizations_url: 'https://api.github.com/users/yuliyakasavec/orgs',
  repos_url: 'https://api.github.com/users/yuliyakasavec/repos',
  events_url: 'https://api.github.com/users/yuliyakasavec/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/yuliyakasavec/received_events',
  type: 'User',
  site_admin: false,
  name: 'Yuliya Kasavets',
  company: '',
  blog: 'www.yuliyakasavets.com',
  location: 'Poland',
  email: null,
  hireable: null,
  bio: 'frontend developer',
  twitter_username: 'yuliya kasavets',
  public_repos: 41,
  public_gists: 0,
  followers: 15,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
