export default [
  {
    createdAt: '2026-04-08T20:23:08Z',
    description: '',
    forks: 1,
    isPrivate: false,
    name: 'github_users',
    nameWithOwner: 'yuliyakasavec/github_users',
    language: 'JavaScript',
    pushedAt: '2026-04-09T19:39:43Z',
    sshUrl: 'git@github.com:yuliyakasavec/github_users.git',
    stargazers_count: 1,
    updatedAt: '2026-04-09T19:39:51Z',
    url: 'https://github.com/yuliyakasavec/github_users',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-03-12T20:49:34Z',
    description: '',
    forks: 3,
    isPrivate: false,
    name: 'jobster',
    nameWithOwner: 'yuliyakasavec/jobster',
    language: 'JavaScript',
    pushedAt: '2026-04-06T17:26:19Z',
    sshUrl: 'git@github.com:yuliyakasavec/jobster.git',
    stargazers_count: 2,
    updatedAt: '2026-04-06T17:26:23Z',
    url: 'https://github.com/yuliyakasavec/jobster',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-03-06T20:27:19Z',
    description: '',
    forks: 2,
    isPrivate: false,
    name: 'jobify-project',
    nameWithOwner: 'yuliyakasavec/jobify-project',
    language: 'TypeScript',
    pushedAt: '2026-03-10T21:29:24Z',
    sshUrl: 'git@github.com:yuliyakasavec/jobify-project.git',
    stargazers_count: 1,
    updatedAt: '2026-03-10T21:29:27Z',
    url: 'https://github.com/yuliyakasavec/jobify-project',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-03-03T11:56:24Z',
    description: '',
    forks: 4,
    isPrivate: false,
    name: 'search-github-users-graphql-project',
    nameWithOwner: 'yuliyakasavec/search-github-users-graphql-project',
    language: 'TypeScript',
    pushedAt: '2026-03-03T18:17:17Z',
    sshUrl:
      'git@github.com:yuliyakasavec/search-github-users-graphql-project.git',
    stargazers_count: 5,
    updatedAt: '2026-03-03T18:17:21Z',
    url: 'https://github.com/yuliyakasavec/search-github-users-graphql-project',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-02-18T19:33:18Z',
    description: '',
    forks: 6,
    isPrivate: false,
    name: 'nextjs-store',
    nameWithOwner: 'yuliyakasavec/nextjs-store',
    language: 'TypeScript',
    pushedAt: '2026-03-02T18:52:12Z',
    sshUrl: 'git@github.com:yuliyakasavec/nextjs-store.git',
    stargazers_count: 9,
    updatedAt: '2026-03-02T18:52:16Z',
    url: 'https://github.com/yuliyakasavec/nextjs-store',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-02-17T20:47:06Z',
    description: '',
    forks: 8,
    isPrivate: false,
    name: 'nextjs-tutorial',
    nameWithOwner: 'yuliyakasavec/nextjs-tutorial',
    language: 'TypeScript',
    pushedAt: '2026-02-17T20:48:24Z',
    sshUrl: 'git@github.com:yuliyakasavec/nextjs-tutorial.git',
    stargazers_count: 10,
    updatedAt: '2026-02-17T20:48:28Z',
    url: 'https://github.com/yuliyakasavec/nextjs-tutorial',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-02-05T20:37:40Z',
    description: '',
    forks: 5,
    isPrivate: false,
    name: 'comfy_store',
    nameWithOwner: 'yuliyakasavec/comfy_store',
    language: 'JavaScript',
    pushedAt: '2026-02-10T13:47:24Z',
    sshUrl: 'git@github.com:yuliyakasavec/comfy_store.git',
    stargazers_count: 15,
    updatedAt: '2026-02-10T13:47:27Z',
    url: 'https://github.com/yuliyakasavec/comfy_store',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-02-03T18:37:56Z',
    description: '',
    forks: 7,
    isPrivate: false,
    name: 'redux-toolkit',
    nameWithOwner: 'yuliyakasavec/redux-toolkit',
    language: 'JavaScript',
    pushedAt: '2026-02-03T18:52:31Z',
    sshUrl: 'git@github.com:yuliyakasavec/redux-toolkit.git',
    stargazers_count: 7,
    updatedAt: '2026-02-03T18:52:51Z',
    url: 'https://github.com/yuliyakasavec/redux-toolkit',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-02-02T14:38:48Z',
    description: '',
    forks: 10,
    isPrivate: false,
    name: 'tailwind-portfolio',
    nameWithOwner: 'yuliyakasavec/tailwind-portfolio',
    language: 'JavaScript',
    pushedAt: '2026-02-02T14:40:30Z',
    sshUrl: 'git@github.com:yuliyakasavec/tailwind-portfolio.git',
    stargazers_count: 5,
    updatedAt: '2026-02-02T14:40:44Z',
    url: 'https://github.com/yuliyakasavec/tailwind-portfolio',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-28T20:38:04Z',
    description: '',
    forks: 12,
    isPrivate: false,
    name: 'mixmaster',
    nameWithOwner: 'yuliyakasavec/mixmaster',
    language: 'JavaScript',
    pushedAt: '2026-01-30T20:46:50Z',
    sshUrl: 'git@github.com:yuliyakasavec/mixmaster.git',
    stargazers_count: 5,
    updatedAt: '2026-01-30T20:46:54Z',
    url: 'https://github.com/yuliyakasavec/mixmaster',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-27T19:18:50Z',
    description: '',
    forks: 9,
    isPrivate: false,
    name: 'contentful-cms',
    nameWithOwner: 'yuliyakasavec/contentful-cms',
    language: 'CSS',
    pushedAt: '2026-01-27T19:21:01Z',
    sshUrl: 'git@github.com:yuliyakasavec/contentful-cms.git',
    stargazers_count: 1,
    updatedAt: '2026-01-27T19:21:05Z',
    url: 'https://github.com/yuliyakasavec/contentful-cms',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-26T20:15:16Z',
    description: '',
    forks: 11,
    isPrivate: false,
    name: 'unsplash_images',
    nameWithOwner: 'yuliyakasavec/unsplash_images',
    language: 'CSS',
    pushedAt: '2026-01-26T20:16:20Z',
    sshUrl: 'git@github.com:yuliyakasavec/unsplash_images.git',
    stargazers_count: 3,
    updatedAt: '2026-01-26T20:16:44Z',
    url: 'https://github.com/yuliyakasavec/unsplash_images',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-24T12:22:53Z',
    description: '',
    forks: 1,
    isPrivate: false,
    name: 'react-query-tasks',
    nameWithOwner: 'yuliyakasavec/react-query-tasks',
    language: 'CSS',
    pushedAt: '2026-01-24T12:23:57Z',
    sshUrl: 'git@github.com:yuliyakasavec/react-query-tasks.git',
    stargazers_count: 4,
    updatedAt: '2026-01-24T12:24:01Z',
    url: 'https://github.com/yuliyakasavec/react-query-tasks',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-21T20:56:03Z',
    description: '',
    forks: 2,
    isPrivate: false,
    name: 'cart',
    nameWithOwner: 'yuliyakasavec/cart',
    language: 'JavaScript',
    pushedAt: '2026-01-21T20:56:52Z',
    sshUrl: 'git@github.com:yuliyakasavec/cart.git',
    stargazers_count: 17,
    updatedAt: '2026-01-21T20:56:56Z',
    url: 'https://github.com/yuliyakasavec/cart',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-20T15:06:12Z',
    description: '',
    forks: 3,
    isPrivate: false,
    name: 'strapi-submenus',
    nameWithOwner: 'yuliyakasavec/strapi-submenus',
    language: 'CSS',
    pushedAt: '2026-01-20T15:10:25Z',
    sshUrl: 'git@github.com:yuliyakasavec/strapi-submenus.git',
    stargazers_count: 3,
    updatedAt: '2026-01-20T15:10:29Z',
    url: 'https://github.com/yuliyakasavec/strapi-submenus',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-19T16:17:49Z',
    description: '',
    forks: 4,
    isPrivate: false,
    name: 'sidebar-modal',
    nameWithOwner: 'yuliyakasavec/sidebar-modal',
    language: 'CSS',
    pushedAt: '2026-01-19T16:19:01Z',
    sshUrl: 'git@github.com:yuliyakasavec/sidebar-modal.git',
    stargazers_count: 1,
    updatedAt: '2026-01-19T16:19:05Z',
    url: 'https://github.com/yuliyakasavec/sidebar-modal',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-16T14:14:37Z',
    description: '',
    forks: 5,
    isPrivate: false,
    name: 'navbar',
    nameWithOwner: 'yuliyakasavec/navbar',
    language: 'CSS',
    pushedAt: '2026-01-16T14:17:29Z',
    sshUrl: 'git@github.com:yuliyakasavec/navbar.git',
    stargazers_count: 6,
    updatedAt: '2026-01-16T14:17:33Z',
    url: 'https://github.com/yuliyakasavec/navbar',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-15T19:22:12Z',
    description: '',
    forks: 2,
    isPrivate: false,
    name: 'grocery-bud',
    nameWithOwner: 'yuliyakasavec/grocery-bud',
    language: 'CSS',
    pushedAt: '2026-01-15T19:23:20Z',
    sshUrl: 'git@github.com:yuliyakasavec/grocery-bud.git',
    stargazers_count: 4,
    updatedAt: '2026-01-15T19:23:25Z',
    url: 'https://github.com/yuliyakasavec/grocery-bud',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-14T20:36:34Z',
    description: '',
    forks: 3,
    isPrivate: false,
    name: 'color-generator',
    nameWithOwner: 'yuliyakasavec/color-generator',
    language: 'CSS',
    pushedAt: '2026-01-14T20:37:57Z',
    sshUrl: 'git@github.com:yuliyakasavec/color-generator.git',
    stargazers_count: 10,
    updatedAt: '2026-01-14T20:38:01Z',
    url: 'https://github.com/yuliyakasavec/color-generator',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-13T20:30:42Z',
    description: '',
    forks: 1,
    isPrivate: false,
    name: 'lorem-ipsum-generator',
    nameWithOwner: 'yuliyakasavec/lorem-ipsum-generator',
    language: 'CSS',
    pushedAt: '2026-01-13T20:32:01Z',
    sshUrl: 'git@github.com:yuliyakasavec/lorem-ipsum-generator.git',
    stargazers_count: 5,
    updatedAt: '2026-01-13T20:32:06Z',
    url: 'https://github.com/yuliyakasavec/lorem-ipsum-generator',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-13T20:05:36Z',
    description: '',
    forks: 7,
    isPrivate: false,
    name: 'slider',
    nameWithOwner: 'yuliyakasavec/slider',
    language: 'JavaScript',
    pushedAt: '2026-01-13T20:07:00Z',
    sshUrl: 'git@github.com:yuliyakasavec/slider.git',
    stargazers_count: 11,
    updatedAt: '2026-01-13T20:07:04Z',
    url: 'https://github.com/yuliyakasavec/slider',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-12T18:42:10Z',
    description: '',
    forks: 5,
    isPrivate: false,
    name: 'tabs',
    nameWithOwner: 'yuliyakasavec/tabs',
    language: 'CSS',
    pushedAt: '2026-01-12T18:44:07Z',
    sshUrl: 'git@github.com:yuliyakasavec/tabs.git',
    stargazers_count: 2,
    updatedAt: '2026-01-12T18:44:11Z',
    url: 'https://github.com/yuliyakasavec/tabs',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-12T16:37:31Z',
    description: '',
    forks: 10,
    isPrivate: false,
    name: 'menu',
    nameWithOwner: 'yuliyakasavec/menu',
    language: 'CSS',
    pushedAt: '2026-01-12T16:38:33Z',
    sshUrl: 'git@github.com:yuliyakasavec/menu.git',
    stargazers_count: 8,
    updatedAt: '2026-01-12T16:38:37Z',
    url: 'https://github.com/yuliyakasavec/menu',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-08T17:16:09Z',
    description: '',
    forks: 9,
    isPrivate: false,
    name: 'questions',
    nameWithOwner: 'yuliyakasavec/questions',
    language: 'CSS',
    pushedAt: '2026-01-08T17:17:44Z',
    sshUrl: 'git@github.com:yuliyakasavec/questions.git',
    stargazers_count: 7,
    updatedAt: '2026-01-08T17:17:48Z',
    url: 'https://github.com/yuliyakasavec/questions',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-07T17:13:24Z',
    description: '',
    forks: 8,
    isPrivate: false,
    name: 'reviews',
    nameWithOwner: 'yuliyakasavec/reviews',
    language: 'CSS',
    pushedAt: '2026-01-07T17:14:37Z',
    sshUrl: 'git@github.com:yuliyakasavec/reviews.git',
    stargazers_count: 4,
    updatedAt: '2026-01-07T17:14:41Z',
    url: 'https://github.com/yuliyakasavec/reviews',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2026-01-07T14:34:52Z',
    description: '',
    forks: 1,
    isPrivate: false,
    name: 'tours',
    nameWithOwner: 'yuliyakasavec/tours',
    language: 'CSS',
    pushedAt: '2026-01-07T14:36:36Z',
    sshUrl: 'git@github.com:yuliyakasavec/tours.git',
    stargazers_count: 2,
    updatedAt: '2026-01-07T14:36:40Z',
    url: 'https://github.com/yuliyakasavec/tours',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2025-12-21T17:29:10Z',
    description: '',
    forks: 6,
    isPrivate: false,
    name: 'birthday_buddy',
    nameWithOwner: 'yuliyakasavec/birthday_buddy',
    language: 'CSS',
    pushedAt: '2025-12-21T17:30:32Z',
    sshUrl: 'git@github.com:yuliyakasavec/birthday_buddy.git',
    stargazers_count: 1,
    updatedAt: '2025-12-21T17:30:35Z',
    url: 'https://github.com/yuliyakasavec/birthday_buddy',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2025-12-09T14:40:42Z',
    description: '',
    forks: 2,
    isPrivate: false,
    name: 'backroads-app',
    nameWithOwner: 'yuliyakasavec/backroads-app',
    language: 'CSS',
    pushedAt: '2025-12-09T14:45:04Z',
    sshUrl: 'git@github.com:yuliyakasavec/backroads-app.git',
    stargazers_count: 14,
    updatedAt: '2025-12-09T14:45:08Z',
    url: 'https://github.com/yuliyakasavec/backroads-app',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2025-10-30T16:28:56Z',
    description: '',
    forks: 4,
    isPrivate: false,
    name: 'Amazon_price_tracker',
    nameWithOwner: 'yuliyakasavec/Amazon_price_tracker',
    language: 'TypeScript',
    pushedAt: '2025-11-06T17:25:55Z',
    sshUrl: 'git@github.com:yuliyakasavec/Amazon_price_tracker.git',
    stargazers_count: 13,
    updatedAt: '2025-11-06T17:25:59Z',
    url: 'https://github.com/yuliyakasavec/Amazon_price_tracker',
    visibility: 'PUBLIC',
  },
  {
    createdAt: '2025-10-10T20:46:38Z',
    description: '',
    forks: 1,
    isPrivate: false,
    name: 'instagram-clone',
    nameWithOwner: 'yuliyakasavec/instagram-clone',
    language: 'TypeScript',
    pushedAt: '2025-10-28T14:11:58Z',
    sshUrl: 'git@github.com:yuliyakasavec/instagram-clone.git',
    stargazers_count: 20,
    updatedAt: '2025-10-28T14:12:02Z',
    url: 'https://github.com/yuliyakasavec/instagram-clone',
    visibility: 'PUBLIC',
  },
];
